module AasmRbs
  class Output
    attr_reader data: String

    def initialize: (Class klass) -> String

    def add_states: (Array[String] states, ?::Hash[untyped, untyped] opts) -> String
    def add_events: (Array[String] events) -> Array[String]
    def add_active_record_relation: () -> String

    def new_line: () -> String
    def finalize: () -> String

    private

    attr_reader klass: Class
    attr_writer data: String

    def add_state_constants: (Array[String] states) -> String
    def add_state_scopes: (Array[String] states) -> String
    def add_predicate_states_methods: (Array[String] states) -> String
  end
end
