---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - vendor/**/*
    - exe/*
  NewCops: enable
  TargetRubyVersion: 3.4
