module AasmRbs
  Rake: untyped # there is yet no Rake official RBS

  def self.load_constants: (String) -> void
  def self.run: (String) -> String?
end

# There are yet no official RBS signatures for the AASM module that gets
# included in our classes. Therefore, the only thing we can do in order to not
# make Steep unhappy is to declare a dummy signature ourself for the #aasm method.
class Class
  def aasm: () -> untyped
end
